/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package banking;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
/**
 *
 * @author sahil
 */
public class day_end extends javax.swing.JInternalFrame implements myvariables
{

    /**
     * Creates new form day_end
     */
    public day_end() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Day_End");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Day  End");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("You are about to End Bank Business Day . Do you want to continue ?");

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jButton2)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try
            {
                Connection myconnection ; 
                myconnection=DriverManager.getConnection(path+place,username,password);
                try
                {
                    String trans = "";
                    int curr_day_amt = 0 , t_amt =0;
                    int sum = 0;
                        // calculate sum of credit , debit , transfer
                    
                    String q2 = "select sum(trans_amount) from account_records where date = ?  ";
                    
                    java.util.Date cdate = new java.util.Date();
                    SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
                    String dt = myformat.format(cdate);
                    
                    PreparedStatement mystatement2 = myconnection.prepareStatement(q2);
                    
                    mystatement2.setString(1,dt);
                   
                    ResultSet myresult2 = mystatement2.executeQuery();

                     if(myresult2.next())
                        {
                             curr_day_amt = myresult2.getInt(1);
                           
                        }
                    
                          // transaction history

                    String q = "select trans,trans_amount from account_records where date = ?  ";
                    
                    java.util.Date cdate2 = new java.util.Date();
                    SimpleDateFormat myformat2 = new SimpleDateFormat("yyyy-MM-dd");
                    String dt2 = myformat2.format(cdate2);
                    
                    PreparedStatement mystatement = myconnection.prepareStatement(q);
                    
                    mystatement.setString(1,dt2);
                   
                    ResultSet myresult = mystatement.executeQuery();
                    
                    t_amt = curr_day_amt;
                    
                        if(myresult.next())
                        {
                            do
                            {
                                 trans = myresult.getString("trans");
                               
                                 if(trans.equals("Withdraw") || trans.equals("Recurrence_Deposit_Closed") || trans.equals("Fixed_Deposit_Closed") )
                                 {
                                    t_amt = t_amt - myresult.getInt("trans_amount"); 
                                 }
                                 

                            }
                            while(myresult.next());
                        }
                       
                        
                       String q3 = "SELECT * from bank_bussiness_details where date = (select max(date) from bank_bussiness_details where date < '" + dt2+"')";
                        
                    PreparedStatement mystatement3 = myconnection.prepareStatement(q3);
                    
                    int pre_t_amt = 0;
                   
                    ResultSet myresult3 = mystatement3.executeQuery();

                        if(myresult3.next())
                        {
                            do
                            {
                                 pre_t_amt = myresult3.getInt("total_amt");
                            
                            }
                            while(myresult3.next());
                        }
                        
                       t_amt = t_amt + pre_t_amt;
                        
                        String q4 = "insert into bank_bussiness_details values(?,?,?,?)";
                        
                        PreparedStatement mystatement4 = myconnection.prepareStatement(q4);
                    
                        
                        mystatement4.setString(1,dt);
                        mystatement4.setString(2,String.valueOf(pre_t_amt));
                        mystatement4.setString(3,String.valueOf(curr_day_amt));
                        mystatement4.setString(4,String.valueOf(t_amt));
                        
                        
                        
                        mystatement4.executeUpdate();
                        
                        JOptionPane.showMessageDialog(rootPane,"Day Ended Successfully .");
                        
                        this.dispose();
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,"Error in Query , "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
                            
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane,"Error in Connection "+e.getMessage());
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
